### PR TITLE
Use sync_to_async() wrapper instead of loop.run_in_executor()

### LINKED ISSUE #1146: podman pull can lead to the pulp db running out of DB connections
**Version**
2.8

**Describe the bug**
podman pull can lead to the pulp db running out of DB connections

**To Reproduce**
1. pull `ansible-automation-platform-21/ee-minimal-rhel8 from RH registry
2.  tag and push it to pulp
3. while true; do podman rmi f3d9f93ce802 --force && podman pull pulp3-source-fedora36.puffy.example.com/ansible-automation-platform-21/ee-minimal-rhel8 --tls-verify=false; done;

After some time db will run out connections 
```
ov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]: pulp [c8a4d88cef6c46d5b2b19fa75c448bbd]: 127.0.0.1 - - [25/Nov/2022:16:19:21 +0000] "GET /v2/ansible-automation-platform-21/ee-minimal-rhel8/blobs/sha256:effb57b1fc3ae4f305b3d985ab85>
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]: django.db.utils.OperationalError: connection to server at "localhost" (::1), port 5432 failed: FATAL:  remaining connection slots are reserved for non-replication superuser connectio>
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     connection = Database.connect(**conn_params)
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     return func(*args, **kwargs)
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     self.connection = self.get_new_connection(conn_params)
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     return func(*args, **kwargs)
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     self.connect()
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     raise dj_exc_value.with_traceback(traceback) from exc_value
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     with self.wrap_database_errors:
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/db/backends/base/base.py", line 218, in ensure_connection
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     return func(*args, **kwargs)
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     self.ensure_connection()
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/db/backends/base/base.py", line 235, in _cursor
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     return self._cursor()
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/db/backends/base/base.py", line 259, in cursor
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     return func(*args, **kwargs)
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     cursor = self.connection.cursor()
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     self._result_cache = list(self._iterable_class(self))
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     self._fetch_all()
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/db/models/query.py", line 262, in __len__
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     num = len(clone)
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/db/models/query.py", line 431, in get
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     return getattr(self.get_queryset(), name)(*args, **kwargs)
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     user = User.objects.get(username=username)
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/home/vagrant/devel/pulp_container/pulp_container/app/token_verification.py", line 102, in authenticate
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     user_auth_tuple = authenticator.authenticate(self)
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/rest_framework/request.py", line 380, in _authenticate
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     self._authenticate()
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/rest_framework/request.py", line 227, in user
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     request.user
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/rest_framework/views.py", line 324, in perform_authentication
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     self.perform_authentication(request)
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/rest_framework/views.py", line 414, in initial
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     self.initial(request, *args, **kwargs)
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     raise exc
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     self.raise_uncaught_exception(exc)
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     response = super().handle_exception(exc)
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/home/vagrant/devel/pulp_container/pulp_container/app/registry_api.py", line 288, in handle_exception
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     response = self.handle_exception(exc)
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     return self.dispatch(request, *args, **kwargs)
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     return view_func(*args, **kwargs)
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:     response = get_response(request)
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]: Traceback (most recent call last):
Nov 25 16:19:21 pulp3-source-fedora36 gunicorn[22135]: The above exception was the direct cause of the following exception:
```

**Expected behavior**

**Additional context**
https://issues.redhat.com/browse/AAH-1977

### PR DESCRIPTION
**Pull request by lubosmj**
closes #1146

### CODE REVIEW

**Comment by lubosmj** [comment]
@ipanova, can this change be added to 2.8? I am worrying why this change was not added to this branch earlier.

**Comment by ipanova** [comment]
@lubosmj this is a good observation, the crux question is  - did you test this change against 3.14?  ;) 

https://pulp.plan.io/issues/9522
https://pulp.plan.io/issues/9538

**Comment by ipanova** [comment]
@dralley can you advise what to do here? Satellite 6.10 seems to be the only version using pulpcore 3.14 but it seems to be in maintenance mode.

**Comment by lubosmj** [comment]
> @lubosmj this is a good observation, the crux question is - did you test this change against 3.14? ;)

Not yet. I tested it against pulpcore v3.15 (the version used in the affected installation) and v3.16.

**Comment by ipanova** [comment]
@lubosmj it's unfortunate but pulp-container 2.8 claims to work with pulpcore 3.14 and 3.15.

**Comment by dralley** [comment]
@ipanova I don't think Satellite users have run into this yet, so it's not a pressing concern.  I also don't really expect any further releases beyond maybe one more that rolls up a couple that are already released.

**Comment by lubosmj** [comment]
I find it funny that there are discrepancies even in Python requirements between pulpcore v3.14 and pulp_container v2.8:

https://github.com/pulp/pulp_container/blob/2.8/setup.py#L20
https://github.com/pulp/pulpcore/blob/3.14/setup.py#L20

**Comment by lubosmj** [comment]
Closing in favour of https://github.com/pulp/pulp_container/pull/1176.

**Pull request closed without merging**
