### PR TITLE
Test streamed scenario

### PR DESCRIPTION
**Pull request by mdellweg**
Requires https://github.com/pulp/pulpcore/pull/2639

[noissue]

AH-1506

### CODE REVIEW

**Comment by ipanova** [comment]
@mdellweg I've seen a PR to pulpcore that introduces a new setting redirect_to_object_storage, I believe pulp_container will need a separate PR since we subclass the Handler. Should a separate  issue be opened for pulp_container? We'd also then need to bump the lower requirement version to pulpcore 3.20

**Comment by mdellweg** [comment]
> @mdellweg I've seen a PR to pulpcore that introduces a new setting redirect_to_object_storage, I believe pulp_container will need a separate PR since we subclass the Handler. Should a separate issue be opened for pulp_container? We'd also then need to bump the lower requirement version to pulpcore 3.20

Yes, yes and yes.
I wanted to make this test fail before we will "fix" it. ;)

**Comment by ipanova** [comment]
> > @mdellweg I've seen a PR to pulpcore that introduces a new setting redirect_to_object_storage, I believe pulp_container will need a separate PR since we subclass the Handler. Should a separate issue be opened for pulp_container? We'd also then need to bump the lower requirement version to pulpcore 3.20
> 
> Yes, yes and yes. I wanted to make this test fail before we will "fix" it. ;)

Ah gotcha, thanks for clarifying and confirming! :+1:

**Review by ipanova — APPROVED** [review]
looks good!

**Comment by mdellweg** [comment]
Converted to draft, because of the pulpcore PR dependency.

**Pull request merged**
