### PR TITLE
Fix nightly failures

### PR DESCRIPTION
**Pull request by lubosmj**
Required PR: https://github.com/pulp/pulpcore/pull/3418

[noissue]

### CODE REVIEW

**Comment by lubosmj** [comment]
This change effectively resolves the failures recorded after merging https://github.com/pulp/pulpcore/commit/0f6f31470e54f527db009c846017746569fd2b85 in pulpcore.

**Review by mdellweg — APPROVED** [review]
I don't see this directly requiring the pulpcore PR referenced. Is that solving another issue?

**Comment by lubosmj** [comment]
@mdellweg, yes, it is solving another issue. The tests in `pulp_container.tests.functional.api.test_rbac_repo_content` were failing because the `delete_orphans_pre` fixture was not cleaning up the orphans.

**Comment by mdellweg** [comment]
> @mdellweg, yes, it is solving another issue. The tests in `pulp_container.tests.functional.api.test_rbac_repo_content` were failing because the `delete_orphans_pre` fixture was not cleaning up the orphans.

I believe in the CI we still set that parameter to 0 globally.

**Comment by mdellweg** [comment]
So, can we merge this?

**Comment by lubosmj** [comment]
> So, can we merge this?

After merging the pulpcore's change, yes.

**Pull request merged**
