### PR TITLE
Adding Github Actions

### PR DESCRIPTION
**Pull request by daviddavis**
[noissue]

### CODE REVIEW

**Comment by dralley** [comment]
Need to add ".ci/**" and ".github/**" to the manifest-ignore section of the pyproject.toml

**Comment by ipanova** [comment]
i think we need to copy these script as well https://github.com/pulp/pulp_container/blob/master/.travis/pre_before_install.sh

**Comment by ipanova** [comment]
and probably this as well https://github.com/pulp/pulp_container/blob/master/.travis/post_docs_test.sh

**Comment by ipanova** [comment]
@daviddavis can you please regenerate the update from plugin_template, there has been merged a fix that removed the hardcoded references to pulp_npm

**Comment by daviddavis** [comment]
I think I've addressed everything.

**Review by ipanova — APPROVED** [review]

**Comment by ipanova** [comment]
thank you :cherries:

**Pull request merged**
