### PR TITLE
Update CI + enable https

### PR DESCRIPTION
**Pull request by fao89**
[noissue]

### CODE REVIEW

**Comment by ipanova** [comment]
:tada:

**Comment by fao89** [comment]
Blocked by https://github.com/pulp/pulp-oci-images/pull/73 or https://github.com/pulp/pulp-oci-images/pull/84

**Comment by fao89** [comment]
@pulp/container-plugin I merged the SSL changes, I rebased this PR, but it is broken.
From the logs, I couldn't understand what is happening, I need help to understand how to fix it

**Comment by mdellweg** [comment]
"413 Request Entity Too Large" There is some `max_request_body_size` (or similar) that needs to be increased i think.

**Comment by ipanova** [comment]
> 413 Request Entity Too Large

it 'is `client_max_body_size` in the nginx setting. the default value is set to 1m

**Comment by fao89** [comment]
from SSL single container image:
```nginx
location /pulp/api/v3/ {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;
            # we don't want nginx trying to do something clever with
            # redirects, we set the Host: header above already.
            proxy_redirect off;
            proxy_pass http://pulp-api;
            client_max_body_size 10m;
        }
```
https://github.com/pulp/pulp-oci-images/blob/latest/assets/ssl_nginx.conf#L75

**Comment by fao89** [comment]
The issue is here: https://github.com/pulp/plugin_template/blob/master/templates/github/.ci/ansible/Containerfile.j2.copy#L26-L27
it wasn't copying the nginx snippet

**Comment by ipanova** [comment]
Thank you @fao89 , this looks good to me! @mdellweg  can you take a look as well?

**Review by mdellweg — APPROVED** [review]

**Pull request merged**
