### PR TITLE
Fix the docs search bar

### PR DESCRIPTION
**Pull request by lubosmj**
[noissue]

### CODE REVIEW

**Comment by lubosmj** [comment]
Inspired by pulp_rpm (https://github.com/pulp/pulp_rpm/commit/9469ce1b4e0475d253df85456ccd6d7e9d9105fc) where the search bar works.

**Comment by lubosmj** [comment]
This should finally resolve the issues with the search bar. I have tested it locally and it works.

**Comment by mdellweg** [comment]
Have you tried using `ci_update_docs: true` and `doc_requirements_from_pulpcore: false` in the plugin template?

**Comment by lubosmj** [comment]
I have not. What you have suggested is used in pulp_file and the search bar does not work.

https://github.com/pulp/pulp_file/blob/main/template_config.yml

**Review by mdellweg — APPROVED** [review]

**Pull request merged**
