### PR TITLE
DOC: index.rst: typo, syntax

### PR DESCRIPTION
**Pull request by westurner**

### CODE REVIEW

**Comment by westurner** [comment]
Hey, where would I ask about Docker Notary / TUF features in regards to the Pulp Container Plugin?

From https://twitter.com/westurner/status/1299542433106202625 ::

> #DockerNotary (#TUF) is justified and necessary because container images sidestep normal OS package integrity verifications (with e.g. GPG) and nobody runs debsums or rpm --verify on images they're trusting with all of their ops.
"Trusted Install Media"

https://docs.docker.com/notary/getting_started/

https://github.com/theupdateframework/specification/blob/master/tuf-spec.md

https://en.wikipedia.org/wiki/The_Update_Framework_(TUF)

**Comment by westurner** [comment]
... I've created an issue for this: "DOC,SEC: Docker Notary / TUF support"
https://pulp.plan.io/issues/7419

**Review by mdellweg — CHANGES_REQUESTED** [review]
Can you please add a line with "[noissue]" to the commit message?

**Comment by westurner** [comment]
I appended `[noissue]` to the commit message and force-pushed to this PR branch.

**Review by ipanova — APPROVED** [review]

**Comment by westurner** [comment]
Thanks

**Pull request merged**
