### PR TITLE
Remove getttext calls within log messages

### LINKED ISSUE #690: Audit log statements for i18n
https://github.com/pulp/pulpcore/issues/2477

### PR DESCRIPTION
**Pull request by lubosmj**
closes #690

### CODE REVIEW

**Comment by lubosmj** [comment]
I am not sure whether we should also refactor i18l messages within RuntimeError exceptions. These types of messages are not directly shown to users but rather to administrators in standard error logs. Do you think I should also remove the remaining `gettext` calls from any other uncaught exceptions (which result in HTTP 500 responses)?

**Comment by mdellweg** [comment]
> I am not sure whether we should also refactor i18l messages within RuntimeError exceptions. These types of messages are not directly shown to users but rather to administrators in standard error logs. Do you think I should also remove the remaining `gettext` calls from any other uncaught exceptions (which result in HTTP 500 responses)?

That is not a bad idea. But i want to see more peoples opinions.

**Comment by ipanova** [comment]
> > I am not sure whether we should also refactor i18l messages within RuntimeError exceptions. These types of messages are not directly shown to users but rather to administrators in standard error logs. Do you think I should also remove the remaining `gettext` calls from any other uncaught exceptions (which result in HTTP 500 responses)?
> 
> That is not a bad idea. But i want to see more peoples opinions.

+1. @bmbouter since you're working on the pulpcore issue

**Comment by lubosmj** [comment]
We concluded that if it is either a log entry or traceback, we should not use i8ln.

**Comment by mdellweg** [comment]
Nitpick `s/getttext/gettext/` in the commit message.

**Pull request merged**
