### PR TITLE
Defer import to avoid circular imports.

### PR DESCRIPTION
**Pull request by jctanner**
```
Traceback (most recent call last):
  File "/venv/bin/django-admin", line 8, in <module>
    sys.exit(execute_from_command_line())
  File "/venv/lib64/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/venv/lib64/python3.9/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/venv/lib64/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/venv/lib64/python3.9/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/venv/lib64/python3.9/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/venv/lib64/python3.9/site-packages/pulp_container/app/models.py", line 28, in <module>
    from pulpcore.plugin.util import gpg_verify
  File "/venv/lib64/python3.9/site-packages/pulpcore/plugin/util.py", line 1, in <module>
    from pulpcore.app.role_util import (  # noqa
  File "/venv/lib64/python3.9/site-packages/pulpcore/app/role_util.py", line 14, in <module>
    from pulpcore.app.models.role import GroupRole, Role, UserRole
  File "/venv/lib64/python3.9/site-packages/pulpcore/app/models/role.py", line 30, in <module>
    class UserRole(BaseModel):
  File "/venv/lib64/python3.9/site-packages/pulpcore/app/models/role.py", line 44, in UserRole
    get_user_model(), related_name="object_roles", on_delete=models.CASCADE
  File "/venv/lib64/python3.9/site-packages/django/contrib/auth/__init__.py", line 170, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL, require_ready=False)
  File "/venv/lib64/python3.9/site-packages/django/apps/registry.py", line 211, in get_model
    app_config.import_models()
  File "/venv/lib64/python3.9/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/app/galaxy_ng/app/models/__init__.py", line 17, in <module>
    from .container import (
  File "/app/galaxy_ng/app/models/container.py", line 11, in <module>
    container_models.ContainerDistribution,
AttributeError: partially initialized module 'pulp_container.app.models' has no attribute 'ContainerDistribution' (most likely due to a circular import)
make: *** [Makefile:108: docker/loaddata] Error 1
```

### CODE REVIEW

**Comment by ipanova** [comment]
Last I recall this issue needs to be properly addressed in galaxy_ng https://github.com/pulp/pulp_container/pull/1084#issuecomment-1265742376
cc @rochacbruno

**Comment by jlmitch5** [comment]
@ipanova this came up in triage.  after talking more there is no way to fix the root cause here as initially thought.  we don't believe there's anyway to get around doing things this way.  if you have a proposal, we are open, but I think we will need to do this this way.

**Comment by ipanova** [comment]
cc'ing @lubosmj and @mdellweg  for visibility here, so this, together with what options there are, can be next time discussed at out cross team collab meeting.

**Comment by lubosmj** [comment]
Can we try updating the ForeignKey initialization in pulpcore first: https://github.com/pulp/pulpcore/blob/e5f3598b0882b98f0abe8dfd99d6a21f2f5e4b16/pulpcore/app/models/role.py#L44?

ref: https://stackoverflow.com/a/24630589

**Comment by jctanner** [comment]
@lubosmj There's another instance of get_user_model in pulpcore/app/role_util.py ...

https://github.com/pulp/pulpcore/blob/main/pulpcore/app/role_util.py#L16

If that is changed to settings.AUTH_USER_MODEL, the workers eventually die with ...

```
galaxy_ng-worker-1       | Process Process-2:
galaxy_ng-worker-1       | Traceback (most recent call last):
galaxy_ng-worker-1       |   File "/usr/lib64/python3.9/multiprocessing/process.py", line 315, in _bootstrap
galaxy_ng-worker-1       |     self.run()
galaxy_ng-worker-1       |   File "/usr/lib64/python3.9/multiprocessing/process.py", line 108, in run
galaxy_ng-worker-1       |     self._target(*self._args, **self._kwargs)
galaxy_ng-worker-1       |   File "/src/pulpcore/pulpcore/tasking/pulpcore_worker.py", line 430, in _perform_task
galaxy_ng-worker-1       |     user = get_users_with_perms(task, with_group_users=False).first()
galaxy_ng-worker-1       |   File "/src/pulpcore/pulpcore/app/role_util.py", line 440, in get_users_with_perms
galaxy_ng-worker-1       |     qs = User.objects.none()
galaxy_ng-worker-1       | AttributeError: 'str' object has no attribute 'objects'
galaxy_ng-worker-1       | pulp [None]: pulpcore.tasking.pulpcore_worker:WARNING: Task process for 0188e358-4af7-7651-bad3-8be3c7764726 exited with non zero exitcode 1.
galaxy_ng-worker-1       | pulp [None]: pulpcore.tasking.pulpcore_worker:INFO: Cleaning up task 0188e358-4af7-7651-bad3-8be3c7764726 and marking as failed. Reason: Task process died unexpectedly with exitcode 1.
```

**Comment by lubosmj** [comment]
closing in favour of https://github.com/pulp/pulpcore/pull/3947

**Pull request closed without merging**
