### PR TITLE
Remove Django pin.

### PR DESCRIPTION
**Pull request by ipanova**
[noissue]

### CODE REVIEW

**Review by goosemania — APPROVED** [review]
:bouquet:

**Review by mdellweg — APPROVED** [review]

**Comment by mdellweg** [comment]
The error here looks like a mismatch of click and rq.

**Comment by mdellweg** [comment]
Maybe we need to add a pin for click<8.

**Comment by ipanova** [comment]
> Maybe we need to add a pin for click<8.

there is a pin in the pulp-smash, i am still not sure what installs click 0.8

**Comment by mdellweg** [comment]
Pulp-smash is outside of the container. This is failing rq inside it.

**Review by mdellweg — APPROVED** [review]

**Pull request closed without merging**
