### PR TITLE
Backports + CI updates

### PR DESCRIPTION
**Pull request by ipanova**

### CODE REVIEW

**Review by lubosmj — APPROVED** [review]

**Comment by mdellweg** [comment]
Looks like you need to backport the mistune fix, too

**Comment by ipanova** [comment]
> Looks like you need to backport the mistune fix, too

what's the fix you're referring to?

**Comment by mdellweg** [comment]
> > Looks like you need to backport the mistune fix, too
> 
> what's the fix you're referring to?

https://github.com/pulp/plugin_template/commit/74b5cb3fbf5d01bb8fed68690bc6c43deb96fb4a

I wonder why, it doesn't seem to be needed for the nightly main build.

**Comment by ipanova** [comment]
> > > Looks like you need to backport the mistune fix, too
> > 
> > 
> > what's the fix you're referring to?
> 
> [pulp/plugin_template@74b5cb3](https://github.com/pulp/plugin_template/commit/74b5cb3fbf5d01bb8fed68690bc6c43deb96fb4a)
> 
> I wonder why, it doesn't seem to be needed for the nightly main build.

I had this already and ci still failed, i pinned to 0.8.4

**Comment by ipanova** [comment]
> > > Looks like you need to backport the mistune fix, too
> > 
> > 
> > what's the fix you're referring to?
> 
> [pulp/plugin_template@74b5cb3](https://github.com/pulp/plugin_template/commit/74b5cb3fbf5d01bb8fed68690bc6c43deb96fb4a)
> 
> I wonder why, it doesn't seem to be needed for the nightly main build.

I guess because pulpcore has it already

**Pull request merged**
